name: My build action requiring more space
on: push

jobs:
  build:
    name: Build my artifact
    runs-on: ubuntu-latest
    steps:
      - name: Before Build
        run: |
          echo "Free space:"
          df -h
          
      - name: Free Up GitHub Actions Ubuntu Runner Disk Space 🔧
        run: |
          sudo rm -rf /usr/local/lib/android || true

      - name: Build
        run: |
          echo "Free space:"
          df -h
