name: Shell command

on: push

jobs: 
  run-shell-command: 
      runs-on: self-hosted
      steps:
        - name: echo a string
          run: echo "Hello world"
        - name: multiple commands
          run: |
            node -v 
            npm -v
